
[envs.docs]
python = "3.12"
dependencies = [
  "jinja2~=3.1",
  "markdown~=3.4",
  "mkdocs~=1.5.3",
  "mkdocs-material~=9.5.3",
  # Plugins
  "mkdocs-minify-plugin~=0.7.2",
  "mkdocs-git-revision-date-localized-plugin~=1.2.2",
  "mkdocstrings-python~=1.7.5",
  "mkdocs-autorefs==0.5.0",
  "mkdocs-redirects~=1.2.1",
  "mkdocs-glightbox~=0.3.5",
  # https://github.com/jimporter/mike/issues/82#issuecomment-1172913929
  "mike @ https://github.com/jimporter/mike/archive/refs/tags/v2.0.0.zip",
  # Extensions
  "mkdocs-click~=0.8.0",
  "pymdown-extensions~=10.3",
  # Necessary for syntax highlighting in code blocks
  "pygments~=2.16.1",
  # Validation
  # https://github.com/linkchecker/linkchecker/pull/669#issuecomment-1267236287
  "linkchecker @ git+https://github.com/linkchecker/linkchecker.git@d9265bb71c2054bf57b8c5734a4825d62505c779",
]
pre-install-commands = [
  "python scripts/install_mkdocs_material_insiders.py",
]
[envs.docs.overrides]
env.GH_TOKEN_MKDOCS_MATERIAL_INSIDERS.env-vars = [
  { key = "MKDOCS_CONFIG", value = "mkdocs.insiders.yml" },
  { key = "MKDOCS_CONFIG", value = "mkdocs.yml", if = [""] },
]
[envs.docs.env-vars]
SOURCE_DATE_EPOCH = "1580601600"
PYTHONUNBUFFERED = "1"
MKDOCS_CONFIG = "mkdocs.yml"
[envs.docs.scripts]
build = "mkdocs build --config-file {env:MKDOCS_CONFIG} --clean --strict {args}"
serve = "mkdocs serve --config-file {env:MKDOCS_CONFIG} --dev-addr localhost:8001 {args}"
ci-build = "mike deploy --config-file {env:MKDOCS_CONFIG} --update-aliases {args}"
validate = "linkchecker --config .linkcheckerrc site"
deploy = "mkdocs gh-deploy --force"
# https://github.com/linkchecker/linkchecker/issues/678
build-check = [
  "build --no-directory-urls",
  "validate",
]