site_name: Autenticami
site_description: Autenticami.
site_author: Nitro Agility S.r.l.
site_url: https://hatch.pypa.io/latest/
# repo_name: 
# repo_url: 
# edit_uri: 
copyright: 'Copyright &copy; Nitro Agility S.r.l. 2023-present'

docs_dir: docs
site_dir: site
theme:
  name: material
  custom_dir: docs/.overrides
  language: en
  favicon: assets/images/logo.jpg
  #logo: assets/images/logo.jpg
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant

nav:
    - Autenticami: 
        - index.md
    - Accounts:
        - Accounts Intro: accounts/index.md
        - Learn the basics:
            - Applications:
                - Applications Intro: accounts/applications/index.md
            - APIs:
                - APIs Intro: accounts/apis/index.md
            - IAM:
                - IAM Intro: accounts/iam/index.md
                - Users: accounts/iam/users.md
                - Roles: accounts/iam/roles.md
                - Permissions: accounts/iam/permissions.md
                - Policies: accounts/iam/policies.md
        - Configurations:
            - Applications: accounts/configurations/applications/application.md
            - APIs: accounts/configurations/apis/api.md
            - IAM:
                - User and Roles: accounts/configurations/iam/user-roles.md
                - Permissions: accounts/configurations/iam/permissions.md
                - Policies: accounts/configurations/iam/policies.md
    - Authenticate:
        - Authenticat Intro: authenticate/index.md
        - Login: authenticate/login.md
        - Single Sign-On: authenticate/sso.md
        - Provision Users:
            - Identity Providers: 
                - Identity Providers Intro: authenticate/identity-providers/index.md
                - Social Identity Providers: authenticate/identity-providers/social/index.md
                - Enterprise Identity Providers: authenticate/identity-providers/enterprise/index.md
            - Database Connections: 
                - Database Connections Intro: authenticate/database-connections/index.md
                - Autenticami Database: authenticate/database-connections/autenticami/index.md
    - Secure:
        - Protect your application:
            - Tokens: 
                - Tokens Intro: secure/protect-your-application/tokens/index.md
                - Token Types:
                    - JWTs:
                        - JWTs Intro: secure/protect-your-application/tokens/token-types/jwt-token/index.md
                        - Creation: secure/protect-your-application/tokens/token-types/jwt-token/creation.md
                        - Validation: secure/protect-your-application/tokens/token-types/jwt-token/validation.md
                        - Claims: secure/protect-your-application/tokens/token-types/jwt-token/claims.md
                - ID Token: secure/protect-your-application/tokens/id-token/index.md
                - Access Token: secure/protect-your-application/tokens/access-token/index.md
                - Refresh Token: secure/protect-your-application/tokens/refresh-token/index.md
            - Manage Secrets: 
                - Manage Secrets Intro: secure/protect-your-application/manage-secrets/index.md
    - Endpoints:
        - Endpoint Intro: endpoints/index.md
        - Console: 
            - Management: endpoints/console/management.md
        - Accounts:
            - Management: 
                - Management Intro: endpoints/accounts/management/index.md
            - OAuth:
                - Authorization: endpoints/accounts/oauth/authorization.md
                - Token: endpoints/accounts/oauth/token.md
                - UserInfo: endpoints/accounts/oauth/userinfo.md
            - OpenID:
                - Configuration: endpoints/accounts/openid/configuration.md
            - Keys:
                - JSON Web Key Set: endpoints/accounts/keys/json-web-key-set.md
    - Troubleshoot:
        - Troubleshoot Intro: troubleshoot/index.md
    - References: references.md

# watch:

plugins:
  # Built-in
  search: {}
  # Extra
  glightbox: {}
  minify:
    minify_html: true
  git-revision-date-localized:
    type: date
    # Required for blog plugin's generated indices
    fallback_to_build_date: true
    exclude:
      - blog/**/*
  mike:
    alias_type: copy
  mkdocstrings:
    default_handler: python
  redirects:
    redirect_maps:

markdown_extensions:
  # Built-in
  - markdown.extensions.abbr:
  - markdown.extensions.admonition:
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
  - markdown.extensions.meta:
  - markdown.extensions.tables:
  - markdown.extensions.toc:
      permalink: true
  # Extra
  - mkdocs-click:
  - pymdownx.arithmatex:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.details:
  - pymdownx.emoji:
      # https://github.com/twitter/twemoji
      # https://raw.githubusercontent.com/facelessuser/pymdown-extensions/master/pymdownx/twemoji_db.py
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      guess_lang: false
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite:
  - pymdownx.keys:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shortener: true
      social_url_shorthand: true
      normalize_issue_symbols: true
      provider: github
      user: pypa
      repo: hatch
  - pymdownx.mark:
  - pymdownx.progressbar:
  - pymdownx.saneheaders:
  - pymdownx.smartsymbols:
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - docs/.snippets
      auto_append:
        - links.txt
        - abbrs.txt
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde:

extra:
  version:
    provider: mike
  social:
extra_css:
  - assets/css/custom.css
  - https://cdn.jsdelivr.net/gh/tonsky/FiraCode@5.2/distr/fira_code.css
extra_javascript:
    - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
    - javascripts/tablesort.js
