site_name: Autenticami
site_description: Autenticami.
site_author: Nitro Agility S.r.l.
site_url: https://hatch.pypa.io/latest/
# repo_name: 
# repo_url: 
# edit_uri: 
copyright: 'Copyright &copy; Nitro Agility S.r.l. 2022-present'
docs_dir: docs
site_dir: site
theme:
  name: material
  custom_dir: docs/.overrides
  language: en
  favicon: assets/images/autenticami-icon-logo.png
  logo: assets/images/autenticami-icon-logo.png
  font:
    text: Roboto
    code: Roboto Mono
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: black
  features:
  - navigation.sections
  - navigation.expand
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.instant
  - content.code.copy
  - content.code.annotate # (1)!
  - content.code.select

nav:
- Autenticami:
  - index.md
  - Getting Started: getting-started.md
- Accounts:
  - accounts/account.md
  - Identities:
    - accounts/identities/identities.md
    - Users and Groups: accounts/identities/users-groups.md
    - Roles: accounts/identities/roles.md
  - Applications:
    - Applications: accounts/applications/applications.md
    - Applicative Hierarchies: accounts/applications/applicative-hierarchies.md
    - Resources: accounts/applications/resources.md
    - Actions: accounts/applications/actions.md
  - Access Management:
    - Permissions and Policies: accounts/access-management/permissions-policies.md
    - Policies Reference: accounts/access-management/policies-reference/index.md
- Authenticate:
  - Authentication: authenticate/authentication-providers/authentication.md
  - Provision Users:
    - authenticate/identity-providers/identity-provider.md
- Secure:
  - Protect your resources:
    - Tokens:
      - Token Based Authentication: secure/protect-your-resources/tokens/index.md
      - ID Token: secure/protect-your-resources/tokens/id-token/index.md
      - Access Token: secure/protect-your-resources/tokens/access-token/index.md
      - Refresh Token: secure/protect-your-resources/tokens/refresh-token/index.md
- Console & Endpoints:
  - Management Console: console-endpoints/console.md
  - Endpoints: console-endpoints/endpoints.md
- Troubleshoot: troubleshoot/index.md
- References: references.md

# watch:
plugins:
  # Built-in
  search: {}
  # Extra
  glightbox: {}
  minify:
    minify_html: true
  git-revision-date-localized:
    type: date
    # Required for blog plugin's generated indices
    fallback_to_build_date: true
    exclude:
    - blog/**/*
  mike:
    alias_type: copy
  mkdocstrings:
    default_handler: python
  redirects:
    redirect_maps:

markdown_extensions:
# Built-in
- markdown.extensions.abbr:
- markdown.extensions.admonition:
- markdown.extensions.attr_list:
- markdown.extensions.footnotes:
- markdown.extensions.meta:
- markdown.extensions.tables:
- markdown.extensions.toc:
    permalink: true
# Extra
- mkdocs-click:
- pymdownx.arithmatex:
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret:
- pymdownx.critic:
- pymdownx.details:
- pymdownx.emoji:
    # https://github.com/twitter/twemoji
    # https://raw.githubusercontent.com/facelessuser/pymdown-extensions/master/pymdownx/twemoji_db.py
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.highlight:
    guess_lang: false
    linenums_style: pymdownx-inline
    use_pygments: true
- pymdownx.inlinehilite:
- pymdownx.keys:
- pymdownx.magiclink:
    repo_url_shortener: true
    repo_url_shorthand: true
    social_url_shortener: true
    social_url_shorthand: true
    normalize_issue_symbols: true
    provider: github
    user: pypa
    repo: hatch
- pymdownx.mark:
- pymdownx.progressbar:
- pymdownx.saneheaders:
- pymdownx.smartsymbols:
- pymdownx.snippets:
    check_paths: true
    base_path:
    - docs/.snippets
    auto_append:
    - links.txt
    - abbrs.txt
- pymdownx.superfences:
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde:

extra:
  version:
    provider: mike
  social:
extra_css:
- assets/css/custom.css
- https://cdn.jsdelivr.net/gh/tonsky/FiraCode@5.2/distr/fira_code.css
extra_javascript:
- https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
- javascripts/tablesort.js
